namespace CinemaApp.Web.Localization;

/// <summary>
/// Lightweight UI string catalog for en-US, hy-AM and ru-RU.
/// Keys are the English fallback text; localized dictionaries override per culture.
/// </summary>
public static class UiStrings
{
    private static readonly Dictionary<string, string> Hy = new()
    {
        ["Movies"] = "Ֆիլմեր",
        ["VIP Pass"] = "VIP Աբոնեմենտ",
        ["Admin Dashboard"] = "Ադմին Պանել",
        ["AI Movie Editor"] = "AI Ֆիլմերի Խմբագրիչ",
        ["Languages"] = "Լեզուներ",
        ["Categories"] = "Կատեգորիաներ",
        ["PRO SUBSCRIBER"] = "PRO ԱՆԴԱՄ",
        ["Upgrade to Pro"] = "Անցնել Pro",
        ["Login"] = "Մուտք",
        ["Register"] = "Գրանցում",
        ["Logout"] = "Ելք",
        ["Pro VIP Plans"] = "Pro VIP Պլաններ",
        ["Swagger API"] = "Swagger API",
        ["FEATURED PREMIERE"] = "ՊՐԵՄԻԵՐԱ",
        ["Stream Movie Now"] = "Դիտել Ֆիլմը",
        ["Unlock Pro Qualities"] = "Ապակողպել Pro Որակները",
        ["New Releases"] = "Նոր Թողարկումներ",
        ["All Genres"] = "Բոլոր Ժանրերը",
        ["Search movies, actors, genres..."] = "Որոնել ֆիլմեր, դերասաններ, ժանրեր...",
        ["Filters"] = "Ֆիլտրեր",
        ["Category"] = "Ժանր",
        ["Year"] = "Տարի",
        ["Any year"] = "Ցանկացած տարի",
        ["Rating"] = "Վարկանիշ",
        ["Any rating"] = "Ցանկացած վարկանիշ",
        ["New"] = "Նորերը",
        ["Top Rated"] = "Բարձր Վարկանիշ",
        ["No movies found"] = "Ֆիլմեր չգտնվեցին",
        ["Try clearing your search query or selecting a different category."] = "Փորձեք մաքրել որոնումը կամ ընտրել այլ ժանր։",
        ["Play"] = "Դիտել",
        ["votes"] = "ձայն",
        ["Not rated"] = "Գնահատված չէ",
        ["Back to Movies"] = "Վերադառնալ Ֆիլմեր",
        ["Playing:"] = "Դիտում եք՝",
        ["Pro Subscription Required"] = "Պահանջվում է Pro Աբոնեմենտ",
        ["Upgrade to Cinema Pro ($9.99/mo)"] = "Անցնել Cinema Pro ($9.99/ամիս)",
        ["Watch in 480p (Free)"] = "Դիտել 480p (Անվճար)",
        ["Select Stream Resolution:"] = "Ընտրել Սթրիմի Որակը՝",
        ["VIP Access Active (Max Quality Unlocked)"] = "VIP Ակտիվ է (Բոլոր Որակները Բացված են)",
        ["Upgrade for 1080p"] = "Անցնել 1080p",
        ["Rate this movie"] = "Գնահատեք Ֆիլմը",
        ["Your rating has been saved"] = "Ձեր գնահատականը զետեղվել է",
        ["minutes"] = "րոպե",
        ["Elevate Your Streaming Experience"] = "Բարձրացրեք Ձեր Դիտման Փորձը",
        ["Standard Tier"] = "Ստանդարտ Պլան",
        ["Cinema Pro Pass"] = "Cinema Pro Աբոնեմենտ",
        ["RECOMMENDED"] = "ԱՌԱՋԱՐԿՎՈՒՄ Է",
        ["Current Plan"] = "Ընթացիկ Պլան",
        ["You are a Cinema Pro VIP!"] = "Դուք Cinema Pro VIP եք!",
        ["Browse Movie Catalog"] = "Դիտել Ֆիլմերի Ցանկը",
        ["Subscribe via Stripe ($9.99/mo)"] = "Բաժանորդագրվել ($9.99/ամիս)",
        ["Access to movie catalog"] = "Հասանելիություն ֆիլմերի ցանկին",
        ["Standard Definition (360p & 480p)"] = "Ստանդարտ Որակ (360p և 480p)",
        ["Multilingual subtitles & metadata"] = "Բազմալեզու ենթագրեր և տվյալներ",
        ["720p & 1080p HD Restricted"] = "720p և 1080p HD Սահմանափակ",
        ["Priority CDN Bandwidth"] = "Առաջնահերթ CDN Թրաֆիկ",
        ["Full 1080p FHD & 720p HD Streaming"] = "Լիարժեք 1080p FHD և 720p HD Սթրիմինգ",
        ["Cross-platform Android App playback"] = "Նվագարկում Android-ում",
        ["Instant zero-buffering byte-range seeking"] = "Ակնթարթային բուֆերացումից զուրկ նվագարկում",
        ["Ad-free cinema immersion"] = "Առանց գովազդի դիտում",
        ["Cancel anytime with 1-click"] = "Չեղարկել ցանկացած պահի",
        ["Sign In"] = "Մուտք",
        ["Sign In to Cinema"] = "Մուտք Գործել",
        ["Email Address"] = "Էլ․ հասցե",
        ["Password"] = "Գաղտնաբառ",
        ["Confirm Password"] = "Կրկնեք Գաղտնաբառը",
        ["Create Account"] = "Ստեղծել Հաշիվ",
        ["Create Free Account"] = "Ստեղծել Անվճար Հաշիվ",
        ["Don't have an account?"] = "Հաշիվ չունե՞ք",
        ["Create one now"] = "Ստեղծեք հիմա",
        ["Already have an account?"] = "Արդեն հաշիվ ունե՞ք",
        ["Demo Credentials:"] = "Դեմո Տվյալներ՝",
        ["Welcome to Cinema Pro!"] = "Բարի Գալուստ Cinema Pro!",
        ["Start Watching in 1080p"] = "Դիտել 1080p-ով",
        ["Subscribe to Pro"] = "Բաժանորդագրվել Pro-ին",
        ["All"] = "Բոլորը",
        ["Apply filters"] = "Կիրառել Ֆիլտրերը",
        ["Remove filters"] = "Մաքրել Ֆիլտրերը",
        ["Clear filters"] = "Մաքրել Ֆիլտրերը",
        ["Active Filters"] = "Ակտիվ Ֆիլտրեր",
        ["ProLockText"] = "Full HD սթրիմինգը Cinema Pro-ի բացառիկ հատկանիշն է։ Հյուրերը կարող են դիտել ստանդարտ որակով (360p և 480p)։",
        ["Access your CinemaApp streaming profile"] = "Մուտք դեպի ձեր CinemaApp սթրիմինգ պրոֆիլ",
        ["Join CinemaApp for personalized streaming"] = "Միացեք CinemaApp-ին անհատականացված դիտման համար",
        ["forever"] = "ընդմիշտ",
        ["month"] = "ամիս",
        ["Your account has been upgraded successfully. Full HD 1080p and 720p streams are now instantly unlocked for your web and Android devices."] = "Ձեր հաշիվը հաջողությամբ թարմացվել է։ 1080p և 720p Full HD սթրիմները անմիջապես բացված են ձեր բոլոր սարքերում։",
    };

    private static readonly Dictionary<string, string> Ru = new()
    {
        ["Movies"] = "Фильмы",
        ["VIP Pass"] = "VIP-абонемент",
        ["Admin Dashboard"] = "Панель администратора",
        ["AI Movie Editor"] = "AI редактор фильмов",
        ["Languages"] = "Языки",
        ["Categories"] = "Категории",
        ["PRO SUBSCRIBER"] = "PRO-ПОДПИСЧИК",
        ["Upgrade to Pro"] = "Перейти на Pro",
        ["Login"] = "Вход",
        ["Register"] = "Регистрация",
        ["Logout"] = "Выход",
        ["Pro VIP Plans"] = "Pro VIP тарифы",
        ["Swagger API"] = "Swagger API",
        ["FEATURED PREMIERE"] = "ПРЕМЬЕРА",
        ["Stream Movie Now"] = "Смотреть фильм",
        ["Unlock Pro Qualities"] = "Открыть Pro качество",
        ["New Releases"] = "Новинки",
        ["All Genres"] = "Все жанры",
        ["Search movies, actors, genres..."] = "Поиск фильмов, актёров, жанров...",
        ["Filters"] = "Фильтры",
        ["Category"] = "Жанр",
        ["Year"] = "Год",
        ["Any year"] = "Любой год",
        ["Rating"] = "Рейтинг",
        ["Any rating"] = "Любой рейтинг",
        ["New"] = "Новые",
        ["Top Rated"] = "Лучшие",
        ["No movies found"] = "Фильмы не найдены",
        ["Try clearing your search query or selecting a different category."] = "Попробуйте изменить запрос или выбрать другой жанр.",
        ["Play"] = "Смотреть",
        ["votes"] = "голосов",
        ["Not rated"] = "Нет оценок",
        ["Back to Movies"] = "Назад к фильмам",
        ["Playing:"] = "Смотрите:",
        ["Pro Subscription Required"] = "Требуется Pro подписка",
        ["Upgrade to Cinema Pro ($9.99/mo)"] = "Перейти на Cinema Pro ($9.99/мес)",
        ["Watch in 480p (Free)"] = "Смотреть 480p (бесплатно)",
        ["Select Stream Resolution:"] = "Выберите разрешение:",
        ["VIP Access Active (Max Quality Unlocked)"] = "VIP активен (все качества открыты)",
        ["Upgrade for 1080p"] = "Обновить до 1080p",
        ["Rate this movie"] = "Оцените фильм",
        ["Your rating has been saved"] = "Ваша оценка сохранена",
        ["minutes"] = "мин",
        ["Elevate Your Streaming Experience"] = "Улучшите качество просмотра",
        ["Standard Tier"] = "Стандартный план",
        ["Cinema Pro Pass"] = "Cinema Pro Pass",
        ["RECOMMENDED"] = "РЕКОМЕНДУЕМ",
        ["Current Plan"] = "Текущий план",
        ["You are a Cinema Pro VIP!"] = "Вы Cinema Pro VIP!",
        ["Browse Movie Catalog"] = "Каталог фильмов",
        ["Subscribe via Stripe ($9.99/mo)"] = "Подписаться ($9.99/мес)",
        ["Access to movie catalog"] = "Доступ к каталогу фильмов",
        ["Standard Definition (360p & 480p)"] = "Стандартное качество (360p и 480p)",
        ["Multilingual subtitles & metadata"] = "Мультиязычные субтитры и данные",
        ["720p & 1080p HD Restricted"] = "720p и 1080p HD ограничены",
        ["Priority CDN Bandwidth"] = "Приоритетный CDN-трафик",
        ["Full 1080p FHD & 720p HD Streaming"] = "Полное 1080p FHD и 720p HD вещание",
        ["Cross-platform Android App playback"] = "Воспроизведение в приложении Android",
        ["Instant zero-buffering byte-range seeking"] = "Мгновенная перемотка без буферизации",
        ["Ad-free cinema immersion"] = "Просмотр без рекламы",
        ["Cancel anytime with 1-click"] = "Отмена в один клик в любое время",
        ["Sign In"] = "Вход",
        ["Sign In to Cinema"] = "Войти",
        ["Email Address"] = "Эл. почта",
        ["Password"] = "Пароль",
        ["Confirm Password"] = "Повторите пароль",
        ["Create Account"] = "Создать аккаунт",
        ["Create Free Account"] = "Создать бесплатный аккаунт",
        ["Don't have an account?"] = "Нет аккаунта?",
        ["Create one now"] = "Создать",
        ["Already have an account?"] = "Уже есть аккаунт?",
        ["Demo Credentials:"] = "Демо-данные:",
        ["Welcome to Cinema Pro!"] = "Добро пожаловать в Cinema Pro!",
        ["Start Watching in 1080p"] = "Смотреть в 1080p",
        ["Subscribe to Pro"] = "Подписаться на Pro",
        ["All"] = "Все",
        ["Apply filters"] = "Применить",
        ["Remove filters"] = "Сбросить фильтры",
        ["Clear filters"] = "Сбросить фильтры",
        ["Active Filters"] = "Активные фильтры",
        ["ProLockText"] = "Полное HD вещание — эксклюзив Cinema Pro. Гости могут смотреть в стандартном качестве (360p и 480p).",
        ["Access your CinemaApp streaming profile"] = "Вход в ваш стриминговый профиль CinemaApp",
        ["Join CinemaApp for personalized streaming"] = "Присоединяйтесь к CinemaApp для персонального просмотра",
        ["forever"] = "навсегда",
        ["month"] = "месяц",
        ["Your account has been upgraded successfully. Full HD 1080p and 720p streams are now instantly unlocked for your web and Android devices."] = "Ваш аккаунт успешно обновлён. Потоки Full HD 1080p и 720p мгновенно открыты на ваших устройствах.",
    };

    public static string Tr(string? culture, string key)
    {
        if (string.IsNullOrWhiteSpace(culture))
            return key;

        return culture.ToLowerInvariant() switch
        {
            "hy" or "hy-am" => Hy.TryGetValue(key, out var hy) ? hy : key,
            "ru" or "ru-ru" => Ru.TryGetValue(key, out var ru) ? ru : key,
            _ => key
        };
    }
}